DROP TABLE IF EXISTS billing_schedules CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS loans CASCADE;
DROP TABLE IF EXISTS borrowers CASCADE;

DROP TYPE IF EXISTS billing_status;
DROP TYPE IF EXISTS loan_status;
